In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
df=pd.read_csv('/content/audible_uncleaned.csv')
print(df.shape)
df.head(5)

(87489, 8)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

## **Column Breakdown**
 - name: Name of the audiobook
 - author: Author of the audiobook
 - narrator: Narrator of the audiobook
 - time: Length of the audiobook
 - releasedate: Release date of the audiobook
 - language: Language of the audiobook
 - stars: No. of stars the audiobook received
 - price: Price of the audiobook in INR


## **Observations**:
   ### **Manual**
  
  ### Dirty Data

*   The audiobook title text contains multiple language. **Consistency**
*   Row no 36 contains the info related to the kind of audiobook with title **Consistency**
-   Row no 159 have mixed english and other language **Consistency**
-   Author coulum have wrttenby: in all the row **Accuracy**
-   Narrator column have written NarratedBY: in all the rows **Accuracy**
-   Date column is having data type string **Validity**
-   Stars column has many missing values **Completeness**
-   Price column has dtata type string **Validity**
-   Language columns have all lower text but English language has E caps **Consistency**
-   Date column have mentioned the date in different format**Validity**
  ### Messy Data


*   The name of the Audiobook is combined with Volume and editition of the audio book **Consistency**
*   The Time column is having hours and minutes, need to handle **Validity** **Consistency**
-   Starts column have stars as well as rating **Validity** **Consistency**



   ### **Coding**

  ### Dirty Data

*   No missing value founds in any of the columns
*   
  ### Messy Data

*   All columns have same data types string **Validity**
*

In [176]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820

In [177]:
df.tail()

,name,author,narrator,time,releasedate,language,stars,price
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569

In [178]:
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price
45055,Star Wars: The Clone Wars,Writtenby:KarenTraviss,Narratedby:JeffGurner,7 hrs and 47 mins,16-09-08,English,5 out of 5 stars1 rating,879
5485,[82巻] The Honest Woodman（金のオノと銀のオノ・英語版）: きいろいとり文庫 その82,Writtenby:YellowBirdProject,Narratedby:Mercedes,10 mins,15-03-21,English,Not rated yet,139
14887,Stars in My Eyes,Writtenby:DavidMorrell,Narratedby:MarcVietor,10 hrs and 11 mins,12-11-19,English,Not rated yet,836
50165,Mitla Pass,Writtenby:LeonUris,"Narratedby:AngelaDawe,DaviddeVries",15 hrs and 41 mins,14-05-19,English,Not rated yet,1005
33471,The Celestine Meditations,Writtenby:SalleMerrillRedfield,Narratedby:SalleMerrillRedfield,1 hr and 1 min,16-12-99,English,Not rated yet,500

In [179]:
df.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

In [180]:
df.duplicated().sum()

np.int64(0)

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

In [182]:
df.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1009
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586
freq,20,874,1034,372,773,61884,72417,5533

In [183]:
len(df['name'].unique())

82767

In [184]:
df.shape

(87489, 8)

In [185]:
df['name'].value_counts()

name
The Art of War                                                                                                       20
Sterling Biographies                                                                                                 19
The Odyssey                                                                                                          16
Sterling Point Books                                                                                                 16
Hamlet                                                                                                               15
                                                                                                                     ..
Resumen de La tercera ola de Steve Case                                                                               1
Resumen de Superventas de Anita Elberse                                                                               1
Resumen de What Great Service Leaders Know & Do de W. Earl Sasser, Jr., Leonard A. Schlesinger y James L. Heskett     1
Resumen de Ventas y Marketing. Un solo corazón de John Jantsch                                                        1
Resumen de Marketing digital que funciona de Nacho Somalo                                                             1
Name: count, Length: 82767, dtype: int64

In [186]:
df[df['name']=='The Art of War']

,name,author,narrator,time,releasedate,language,stars,price
15112,The Art of War,Writtenby:SunTzu,Narratedby:PhillipJMather,1 hr and 8 mins,11-12-15,English,Not rated yet,333
27377,The Art of War,Writtenby:SunTzu,Narratedby:AidanGillen,1 hr and 7 mins,31-03-15,English,4 out of 5 stars511 ratings,333
27977,The Art of War,Writtenby:SunTzu,Narratedby:MelFoster,1 hr and 23 mins,06-12-16,English,4 out of 5 stars4 ratings,333
27995,The Art of War,Writtenby:SunTzu,Narratedby:DenmaTranslationGroup,3 hrs and 51 mins,12-08-16,English,5 out of 5 stars1 rating,501
29508,The Art of War,Writtenby:SunTzu,Narratedby:AlecSand,1 hr and 46 mins,18-09-09,English,4 out of 5 stars4 ratings,268
29673,The Art of War,Writtenby:SunTzu,"Narratedby:DonHagen,VictoriaGordon",6 hrs and 29 mins,22-09-11,English,3.5 out of 5 stars3 ratings,668
29777,The Art of War,"Writtenby:ThomasCleary-translator,SunTzu",Narratedby:LloydJames,1 hr and 54 mins,03-04-18,English,5 out of 5 stars6 ratings,377
30158,The Art of War,Writtenby:SunTzu,Narratedby:MikeBorris,1 hr and 48 mins,01-11-11,English,4 out of 5 stars1 rating,333
38116,The Art of War,"Writtenby:IntroductionbyStefanRudnicki,SunTzu","Narratedby:RonSilver,B.D.Wong",2 hrs and 15 mins,16-12-99,English,5 out of 5 stars1 rating,333
38227,The Art of War,Writtenby:SunTzu,Narratedby:SethThompson,6 hrs and 35 mins,01-04-20,English,2 out of 5 stars2 ratings,258
38355,The Art of War,Writtenby:SunTzu,Narratedby:GrainneRegan,1 hr and 9 mins,12-12-18,English,Not rated yet,65
38779,The Art of War,Writtenby:SunTzu,Narratedby:KennethElliot,1 hr and 22 mins,04-03-20,English,4.5 out of 5 stars2 ratings,32
38849,The Art of War,Writtenby:SunTzu,Narratedby:DanStrutzel,1 hr and 38 mins,28-04-21,English,Not rated yet,1003
38961,The Art of War,Writtenby:SunTzu,Narratedby:GabraZackman,1 hr and 42 mins,07-01-20,English,Not rated yet,702
39224,The Art of War,"Writtenby:LionelGilestranslator,SunTzu",Narratedby:DenisDaly,1 hr and 23 mins,31-07-17,English,Not rated yet,333
40227,The Art of War,Writtenby:SunTzu,Narratedby:JimDonaldson,1 hr and 13 mins,11-08-11,English,Not rated yet,333
40299,The Art of War,Writtenby:SunTzu,Narratedby:ElizabethAnneHarris,1 hr and 12 mins,23-07-21,English,Not rated yet,132
41246,The Art of War,Writtenby:SunTzu,Narratedby:SimonVance,2 hrs and 6 mins,13-08-19,English,Not rated yet,456
41545,The Art of War,Writtenby:SunTzu,Narratedby:MikeVendetti,1 hr and 12 mins,13-03-20,English,Not rated yet,286
65687,The Art of War,Writtenby:SunTzu,Narratedby:PaulSpera,1 hr and 8 mins,21-02-18,English,Not rated yet,233

In [187]:
pd.set_option('display.max_columns', None)

In [188]:
df['price']=df['price'].str.strip().str.split('.').str.get(0)

In [189]:
df['price'].str.strip().replace(',',''  ,inplace=True)

In [190]:
df['price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 87489 entries, 0 to 87488
Series name: price
Non-Null Count  Dtype
--------------  -----
87489 non-null  object
dtypes: object(1)
memory usage: 683.6+ KB

In [191]:
df['price']=df['price'].apply(lambda x:x.replace(',',''))

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

In [193]:
df1=df.copy()

In [194]:
temp_df=df1[df1['price']=='Free']
df1.loc[temp_df.index,'price']=0
df1['price']=df1['price'].astype(float)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  float64
dtypes: float64(1), object(7)
memory usage: 5.3+ MB

In [195]:
df1['author']=df1['author'].str.strip().str.split(':').str.get(1)

In [196]:
df1['narrator']=df1['narrator'].str.strip().str.split(':').str.get(1)

In [197]:
df1['language']=df1['language'].str.lower()

In [198]:
df1['stars'].value_counts()

stars
Not rated yet                      72417
5 out of 5 stars1 rating            3739
4 out of 5 stars1 rating            1254
5 out of 5 stars2 ratings            998
4.5 out of 5 stars2 ratings          661
                                   ...
4.5 out of 5 stars1,636 ratings        1
4.5 out of 5 stars328 ratings          1
4.5 out of 5 stars168 ratings          1
5 out of 5 stars1,425 ratings          1
4.5 out of 5 stars292 ratings          1
Name: count, Length: 665, dtype: int64

In [199]:
def star_rating(text):
  if text=='Not rated yet':
    return '0:0'
  else:
    return text.replace('out of 5 stars',':').replace('ratings','').replace('rating','')

In [200]:
df1['star']=df1['stars'].apply(star_rating).str.strip().str.split(':').str.get(0)
df1['ratings']=df1['stars'].apply(star_rating).str.strip().str.split(':').str.get(1)

In [201]:
df1.head()

,name,author,narrator,time,releasedate,language,stars,price,star,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,english,5 out of 5 stars34 ratings,468.0,5,34
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,english,4.5 out of 5 stars41 ratings,820.0,4.5,41
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,06-11-20,english,4.5 out of 5 stars38 ratings,410.0,4.5,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,05-10-21,english,4.5 out of 5 stars12 ratings,615.0,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,13-01-10,english,4.5 out of 5 stars181 ratings,820.0,4.5,181

In [202]:
df1['star']=df1['star'].astype(float)
df1['ratings']=df1['ratings'].str.replace(',','').astype(float)

In [203]:
df1.drop('stars',axis=1,inplace=True)

In [204]:
df1.head(5)

,name,author,narrator,time,releasedate,language,price,star,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,english,468.0,5.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,english,820.0,4.5,41.0
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,06-11-20,english,410.0,4.5,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,05-10-21,english,615.0,4.5,12.0
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,13-01-10,english,820.0,4.5,181.0

In [205]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   price        87489 non-null  float64
 7   star         87489 non-null  float64
 8   ratings      87489 non-null  float64
dtypes: float64(3), object(6)
memory usage: 6.0+ MB

In [206]:
df1.sample(10)

,name,author,narrator,time,releasedate,language,price,star,ratings
70933,The Number of Love,RoseannaM.White,SusanLyons,14 hrs and 21 mins,06-06-19,english,1055.0,0.0,0.0
64653,Madison's Sorrow,KevinO’Leary,BrandonMassey,12 hrs and 45 mins,03-01-22,english,657.0,0.0,0.0
32436,Close to the Bone,JeanShinodaBolenM.D.,JeanShinodaBolenM.D.,2 hrs and 49 mins,17-11-17,english,444.0,0.0,0.0
76115,"Kika, nada pasa hasta que pasa",LeticiaOrtizMarín,EvaColl,10 hrs and 40 mins,20-09-21,spanish,691.0,0.0,0.0
21983,Scholars of Mayhem,"DanielC.Guiet,TimothyK.Smith",RobertFass,7 hrs and 2 mins,04-06-19,english,879.0,0.0,0.0
74367,Nitro (German edition),InkaLoreenMinden,"SandraBecker,OllieWeiberg",6 hrs and 22 mins,20-05-21,german,367.0,0.0,0.0
53193,To Build a Fire,JackLondon,JohnLingua,33 mins,10-11-21,english,32.0,0.0,0.0
64588,Пережить холодную войну. Опыт дипломатии,АлександрГольц,ДмитрийВеликанов,10 hrs and 20 mins,03-02-22,russian,267.0,0.0,0.0
67537,The Gods Never Left Us,ErichvonDäniken,SeanRunnette,5 hrs and 31 mins,20-11-17,english,820.0,4.0,5.0
68687,Inner Christianity,RichardSmoley,RichardSmoley,9 hrs and 34 mins,08-05-07,english,879.0,0.0,0.0

In [207]:
df1.head(5)

,name,author,narrator,time,releasedate,language,price,star,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,english,468.0,5.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,english,820.0,4.5,41.0
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,06-11-20,english,410.0,4.5,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,05-10-21,english,615.0,4.5,12.0
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,13-01-10,english,820.0,4.5,181.0

In [208]:
df1['time']=df1['time'].str.strip().str.replace('hrs','h').str.replace('hr','h').str.replace('mins','m').str.replace('min','m')

In [209]:
df1

,name,author,narrator,time,releasedate,language,price,star,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 h and 20 m,04-08-08,english,468.0,5.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,13 h and 8 m,01-05-18,english,820.0,4.5,41.0
2,The Deep End,JeffKinney,DanRussell,2 h and 3 m,06-11-20,english,410.0,4.5,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 h and 16 m,05-10-21,english,615.0,4.5,12.0
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 h,13-01-10,english,820.0,4.5,181.0
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,7 h and 34 m,09-03-17,english,596.0,0.0,0.0
87485,The Alps,StephenO'Shea,RobertFass,10 h and 7 m,21-02-17,english,820.0,0.0,0.0
87486,The Innocents Abroad,MarkTwain,FloGibson,19 h and 4 m,30-12-16,english,938.0,0.0,0.0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,4 h and 8 m,23-02-11,english,680.0,0.0,0.0
87488,Havana,MarkKurlansky,FleetCooper,6 h and 1 m,07-03-17,english,569.0,0.0,0.0

In [211]:
temp_df1=df1[~df1['time'].str.contains('and')]
temp_df2=df1[df1['time'].str.contains('and')]

In [213]:
temp_df2

,name,author,narrator,time,releasedate,language,price,star,ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 h and 20 m,04-08-08,english,468.0,5.0,34.0
1,The Burning Maze,RickRiordan,RobbieDaymond,13 h and 8 m,01-05-18,english,820.0,4.5,41.0
2,The Deep End,JeffKinney,DanRussell,2 h and 3 m,06-11-20,english,410.0,4.5,38.0
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 h and 16 m,05-10-21,english,615.0,4.5,12.0
5,The Hunger Games: Special Edition,SuzanneCollins,TatianaMaslany,10 h and 35 m,30-10-18,english,656.0,5.0,72.0
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,7 h and 34 m,09-03-17,english,596.0,0.0,0.0
87485,The Alps,StephenO'Shea,RobertFass,10 h and 7 m,21-02-17,english,820.0,0.0,0.0
87486,The Innocents Abroad,MarkTwain,FloGibson,19 h and 4 m,30-12-16,english,938.0,0.0,0.0
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,4 h and 8 m,23-02-11,english,680.0,0.0,0.0
87488,Havana,MarkKurlansky,FleetCooper,6 h and 1 m,07-03-17,english,569.0,0.0,0.0

In [214]:
def time_conv(text):
  if 'Less' in text:
    return 30
  elif 'h'in text:
    hr=text.split(' ')
    return int(hr[0])*60
  elif 'm' in text:
    min=text.split(' ')
    return int(min[0])
  else:
    return int(text)

In [231]:
t1=temp_df2['time'].str.strip().str.split('and').str.get(0).apply(time_conv)

0         20 m
1          8 m
2          3 m
3         16 m
5         35 m
         ...
87484     34 m
87485      7 m
87486      4 m
87487      8 m
87488      1 m
Name: time, Length: 72740, dtype: object

In [238]:
t2=temp_df2['time'].str.strip().str.split('and').str.get(1)
t2=t2.str.strip().apply(time_conv)

In [241]:
temp_df2['time']=t1+t2

/tmp/ipython-input-1187270745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df2['time']=t1+t2

In [242]:
temp_df2['time']

0         140
1         788
2         123
3         676
5         635
         ...
87484     454
87485     607
87486    1144
87487     248
87488     361
Name: time, Length: 72740, dtype: int64

In [244]:
temp_df1['time']=temp_df1['time'].str.strip().apply(time_conv)

/tmp/ipython-input-572063834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df1['time']=temp_df1['time'].str.strip().apply(time_conv)

In [245]:
temp_df1['time']

4        600
53        22
63        13
71        33
77        43
        ...
87451      9
87455    300
87459     48
87471     31
87473     42
Name: time, Length: 14749, dtype: int64

In [246]:
df1.loc[temp_df1.index,'time']=temp_df1['time']
df1.loc[temp_df2.index,'time']=temp_df2['time']

In [250]:
df1['time']=df1['time'].astype(int)

In [254]:
df1['releasedate']=pd.to_datetime(df1['releasedate'])

/tmp/ipython-input-2266741047.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1['releasedate']=pd.to_datetime(df1['releasedate'])

In [256]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  int64
 4   releasedate  87489 non-null  datetime64[ns]
 5   language     87489 non-null  object
 6   price        87489 non-null  float64
 7   star         87489 non-null  float64
 8   ratings      87489 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 6.0+ MB

In [258]:
df1.to_csv('audible_cleaned1.csv',index=False)